[package]
name = "minidsp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
hound = "3.5.1"
libm = "0.2.15"
rand = "0.9.2"
rand_distr = "0.5.1"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
